const SelectedContact =[

    { id: 1, name: 'Alice Cooper', phone: '555-1234', email: 'alice@example.com' },
    { id: 2, name: 'Bob Burger', phone: '555-2345', email: 'bob@example.com' },
    { id: 3, name: 'Charlie Brown', phone: '555-3456', email: 'charlie@example.com' },
    { id: 4, name: 'Diana Pumpernickle', phone: '555-4567', email: 'diana@example.com' },
    { id: 5, name: 'Edward King', phone: '555-5678', email: 'edward@example.com' },
    { id: 6, name: 'Fiona Green', phone: '555-6789', email: 'fiona@example.com' },
    { id: 7, name: 'George Washington', phone: '555-7890', email: 'george@example.com' },
  ];

  export default SelectedContact;


//Psuedo Code 
  // Step 1 was to create a file call SelectedContact.JSX in order for the selectcontact to exist in the react 
  // Just like puppy pal data.JS the SelectedContact is the variable that has to be declared in an array 
  //within that array is the data of the Selected Contact Id , Contact, name, Contact phone and Contact email.
  // then at the end it has to be exported 
  // the SelectedContactId has to be passed in the both the app.jsx and contactlist.jsx as a set component and within the useState 

  